name: Go_Chat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: build and release to DockerHub
      env:
        REPO: soosungp33 # 계정 명
        LAYER_NAME: actiontest # 레포 이름
      run: |
        docker build -t $LAYER_NAME .
        docker tag $LAYER_NAME:latest $REPO/$LAYER_NAME:latest
        docker push $REPO/$LAYER_NAME:latest